# This is a basic workflow to help you get started with Actions

name: CI-libfec

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          set -x -e
          cd plutosdr-fw          
          make -C buildroot ARCH=arm zynq_pluto_defconfig
          make -C buildroot batctl
          cd ..   
          export PATH=`pwd`/plutosdr-fw/buildroot/output/host/bin:`pwd`/plutosdr-fw/buildroot/output/host/sbin:${PATH}
          export CROSS_COMPILE="arm-linux-gnueabihf-"
          which ${CROSS_COMPILE}gcc
          mkdir third_party
          cd third_party
          git clone https://github.com/tvelliott/libfec.git
          cd libfec          
          rm libfec.so
          make
          
